### ISSUE TITLE
総合ステータス/カテゴリ別ステータス計算

### ISSUE THREAD

**Issue by knknk98** [Eri-0910/tamagocchi#19]

**Comment by Eri-0910** [comment]
## メモより

カテゴリ別ステータスの平均（％）
12%でハート1つ　40％で死ぬ
100%~88% 88~76 76~64 64~52 52~40


食べる
前の日までのステータスが今日のステータスになる
たりてないタスクの数 < やりすぎてるタスク = デブ
やりすぎてるタスクの数 < たりてないタスク = やせ

運動・勉強
前の日までのステータスが今日のステータスになる

お風呂・洗濯・掃除
昨日できてなくても、今日やったら改善

**Comment by Eri-0910** [comment]
全体ステータスは計算できた。
カテゴリステータスも計算する術はあるので、あとはイラスト作ってからロジック描く。
